package com.razorpay.risktrace.enums;

public enum EvidenceType {
    RECEIPT, TRACKING_NUMBER, CUSTOMER_COMMUNICATION, REFUND_POLICY, LOG_DATA, OTHER, SHIPPING_PROOF, AUTHORIZATION_LOG, MERCHANT_UPLOADED
}
